In [ ]:
## Constants in tensorflow
#### Constant is a method  in tensorflow is immutable because we cannot change. 

### Import tensorflow library

In [1]:
import tensorflow as tf

### Check version of tensorflow

In [2]:
tf.__version__

'2.6.0'

### Check for tensorflow for gpu

In [3]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

### Create constant in tensorflow

In [4]:
a=tf.constant(20)

In [5]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [6]:
a1=tf.constant(30, dtype=None)

In [7]:
a1

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [8]:
b=tf.constant('Amir khan')

In [9]:
b

<tf.Tensor: shape=(), dtype=string, numpy=b'Amir khan'>

In [10]:
c=tf.constant(True)

In [11]:
c

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [12]:
import numpy as np

In [14]:
a=np.array([[2, 3, 4], [4, 5, 6], [7, 8, 9]])

In [15]:
a

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
c=tf.constant(a)

In [17]:
c

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])>

### Import pandas library

In [18]:
import pandas as pd

### Read csv file 

In [20]:
Df=pd.read_csv('C:/Users/ASAD/Downloads/Compressed/complaints.csv')

C:\Users\ASAD\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [21]:
Df

Date received                                            Product  \
0          2022-02-02  Credit reporting, credit repair services, or o...   
1          2022-03-14  Credit reporting, credit repair services, or o...   
2          2022-03-14  Credit reporting, credit repair services, or o...   
3          2022-03-14  Credit reporting, credit repair services, or o...   
4          2022-03-16                                           Mortgage   
...               ...                                                ...   
2584129    2017-02-09                                    Debt collection   
2584130    2015-04-29                                           Mortgage   
2584131    2017-03-31                                   Credit reporting   
2584132    2017-01-16                                   Credit reporting   
2584133    2018-03-07                                           Mortgage   

                         Sub-product  \
0                   Credit reporting   
1                   Credit reporting   
2                   Credit reporting   
3                   Credit reporting   
4         Conventional home mortgage   
...                              ...   
2584129                I do not know   
2584130  Conventional fixed mortgage   
2584131                          NaN   
2584132                          NaN   
2584133       Other type of mortgage   

                                                     Issue  \
0        Problem with a credit reporting company's inve...   
1                     Incorrect information on your report   
2        Problem with a credit reporting company's inve...   
3        Problem with a credit reporting company's inve...   
4                           Trouble during payment process   
...                                                    ...   
2584129              Cont'd attempts collect debt not owed   
2584130           Loan modification,collection,foreclosure   
2584131           Credit reporting company's investigation   
2584132             Incorrect information on credit report   
2584133                     Trouble during payment process   

                                                 Sub-issue  \
0                     Investigation took more than 30 days   
1                      Information belongs to someone else   
2                     Investigation took more than 30 days   
3        Their investigation did not fix an error on yo...   
4                                                      NaN   
...                                                    ...   
2584129                  Debt resulted from identity theft   
2584130                                                NaN   
2584131           No notice of investigation status/result   
2584132                                     Account status   
2584133                                                NaN   

                              Consumer complaint narrative  \
0                                                      NaN   
1                                                      NaN   
2                                                      NaN   
3                                                      NaN   
4                                                      NaN   
...                                                    ...   
2584129  I have disputed my debts several times with no...   
2584130  My father died in XX/XX/XXXX. Left me his only...   
2584131  cfbp i would Like to file a complaint on Exper...   
2584132  My husband and I are in the middle of an FHA S...   
2584133                                                NaN   

                                   Company public response  \
0        Company has responded to the consumer and the ...   
1                                                      NaN   
2                                                      NaN   
3                                                      NaN   
4        Company has responded to the consumer and the ...   
...    

### Create Data received column in the dataframe as a constant

In [23]:
c=tf.constant(Df['Date received'])

In [24]:
c

<tf.Tensor: shape=(2584134,), dtype=string, numpy=
array([b'2022-02-02', b'2022-03-14', b'2022-03-14', ..., b'2017-03-31',
       b'2017-01-16', b'2018-03-07'], dtype=object)>

In [28]:
a = tf.constant([2, 3, 4, 5], shape=(2, 2), dtype="float32")

In [29]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [34]:
b = tf.constant([2, 3, 4, 5], shape=(2, 2))
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [43]:
a = tf.constant([[[[2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [6, 7, 8, 9]]]], dtype="float32")

In [44]:
a

<tf.Tensor: shape=(1, 1, 4, 4), dtype=float32, numpy=
array([[[[2., 3., 4., 5.],
         [3., 4., 5., 6.],
         [4., 5., 6., 7.],
         [6., 7., 8., 9.]]]], dtype=float32)>

In [37]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [38]:
a.shape

TensorShape([1, 1, 4, 4])

In [39]:
a.numpy()

array([[[[2., 3., 4., 5.],
         [3., 4., 5., 6.],
         [4., 5., 6., 7.],
         [6., 7., 8., 9.]]]], dtype=float32)

In [42]:
a.ndim

4

In [45]:
a.dtype

tf.float32