## Spars tensor

Tensor that contain mostly zero values is called "Spars Tensor".

In [1]:
import tensorflow as tf

## Version of tensorflow

In [2]:
tf.__version__

'2.6.0'

## Syntax of spars tensor
tf.spars.SparsTensor(indices, values, dense_shape)

## Create tensorflow Spars Tensor

In [6]:
st1=tf.SparseTensor(indices=[[0, 2], [3, 4]], values=[10, 20], dense_shape=[2, 10])
print(st1)

SparseTensor(indices=tf.Tensor(
[[0 2]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 2 10], shape=(2,), dtype=int64))


## Create Spars tensor from Dense

In [7]:
import numpy as np

In [8]:
np_array = np.array([[1, 0, 0, 0],
                     [0, 0, 0, 0],
                     [0, 0, 2, 0],
                     [0, 0, 0, 4]])
print(np_array)

[[1 0 0 0]
 [0 0 0 0]
 [0 0 2 0]
 [0 0 0 4]]


In [10]:
tf_2=tf.sparse.from_dense(np_array)
tf_2

In [11]:
print(tf_2)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 4], shape=(3,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))


## Extract the values, indices and shape of Spars Tensor

In [12]:
tf_2.values.numpy().tolist()

[1, 2, 4]

In [15]:
tf_2.indices

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[0, 0],
       [2, 2],
       [3, 3]], dtype=int64)>

In [16]:
tf_2.indices.numpy().tolist()

[[0, 0], [2, 2], [3, 3]]

In [17]:
tf_2.shape

TensorShape([4, 4])

In [18]:
tf_2.dense_shape.numpy().tolist()

[4, 4]

## Spars Tensor to Dense

if the most of the element are non zero then the Tensor is considered Dense

In [19]:
dt_fst=tf.sparse.to_dense(tf_2)
dt_fst

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])>

## Convert Dense Tensor into numpy array

In [20]:
dt_fst.numpy()

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

## Mathematical operation on Spars Tensor

In [21]:
st_add=tf.sparse.add(tf_2, tf_2)
st_add

In [22]:
print(st_add)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2 4 8], shape=(3,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))


In [24]:
tf.sparse.to_dense(st_add).numpy()

array([[2, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 8]])