## Deep learning variables
#### Deep learning tensorflow variables is mutable because we can be change it.

### Import library tensorflow

In [1]:
import tensorflow as tf

### Create variables integer, string, float and boolean

In [31]:
tf_int=tf.Variable([1, 2, 3, 4, 5, 6])
tf_int

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [32]:
tf2_int=tf.Variable(20)
tf2_int

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

In [33]:
tf_float=tf.Variable(10.5)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.5>

In [34]:
tf_str=tf.Variable('Asad')
tf_str

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Asad'>

In [10]:
a=tf.Variable([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
a

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])>

### Check for the name if variable or not?

In [15]:
a.name

'Variable:0'

### Find data type of the variable

In [16]:
a.dtype

tf.int32

### Convert tensorflow variable into numpy array

In [18]:
a.numpy()

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### Boolean variable in tensorflow

In [35]:
tf_bool = tf.Variable([True, False, True, False], [True, False, False, True])
tf_bool

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([ True, False,  True, False])>

### Complex numbers in tensorflow variables and its dtype and then convert to numpy array

In [38]:
tf_complex = tf.Variable([4 + 5j])
tf_complex

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([4.+5.j])>

In [39]:
tf_complex.dtype

tf.complex128

In [40]:
tf_complex.numpy()

array([4.+5.j])

### Change tensoflow variable into constant

In [42]:
tf_cons = tf.constant(tf_complex)
tf_cons

<tf.Tensor: shape=(1,), dtype=complex128, numpy=array([4.+5.j])>

### Create tensorflow constant and then convert into tensorflow variable 

In [43]:
tf_const =tf.constant([[1, 2, 3, 4],[5, 6, 7, 8]])
tf_const

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

### Reshape the above constant

In [45]:
tf.reshape(tf_const, shape=(4, 2))

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])>

In [46]:
tf_var = tf.Variable(tf_const)
tf_var

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

### Get maximum value index from any variable in tensorflow

In [47]:
tf_var

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [49]:
tf_max_index=tf.argmax(tf_var)
tf_max_index

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 1, 1, 1], dtype=int64)>

In [50]:
tf_max_index.numpy()

array([1, 1, 1, 1], dtype=int64)

In [51]:
tf_min_index = tf.argmin(tf_var)
tf_min_index

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 0, 0, 0], dtype=int64)>

In [52]:
tf_min_index.numpy()

array([0, 0, 0, 0], dtype=int64)

### Variable convert to a tensor

In [53]:
tf_var

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [54]:
tf.convert_to_tensor(tf_var)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [55]:
tf_var1 =tf_var
tf_var1

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

### Assign new values to tf_var tensor

In [56]:
tf_new_values=tf_var1.assign([[2, 4, 6, 8], [2, 3, 5, 8]])
tf_new_values

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=int32, numpy=
array([[2, 4, 6, 8],
       [2, 3, 5, 8]])>

### Assign add variable

In [61]:
tf_new_values.assign_add([[2, 4, 6, 8], [2, 3, 5, 8]])

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=int32, numpy=
array([[ 4,  8, 12, 16],
       [ 4,  6, 10, 16]])>

### Import pandas library and read csv file for applyig variable function of tensorflow

In [19]:
import pandas as pd

In [20]:
Df=pd.read_csv('C:/Users/ASAD/Downloads/Compressed/complaints.csv')

C:\Users\ASAD\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [21]:
Df

Date received                                            Product  \
0          2022-02-02  Credit reporting, credit repair services, or o...   
1          2022-03-14  Credit reporting, credit repair services, or o...   
2          2022-03-14  Credit reporting, credit repair services, or o...   
3          2022-03-14  Credit reporting, credit repair services, or o...   
4          2022-03-16                                           Mortgage   
...               ...                                                ...   
2584129    2017-02-09                                    Debt collection   
2584130    2015-04-29                                           Mortgage   
2584131    2017-03-31                                   Credit reporting   
2584132    2017-01-16                                   Credit reporting   
2584133    2018-03-07                                           Mortgage   

                         Sub-product  \
0                   Credit reporting   
1                   Credit reporting   
2                   Credit reporting   
3                   Credit reporting   
4         Conventional home mortgage   
...                              ...   
2584129                I do not know   
2584130  Conventional fixed mortgage   
2584131                          NaN   
2584132                          NaN   
2584133       Other type of mortgage   

                                                     Issue  \
0        Problem with a credit reporting company's inve...   
1                     Incorrect information on your report   
2        Problem with a credit reporting company's inve...   
3        Problem with a credit reporting company's inve...   
4                           Trouble during payment process   
...                                                    ...   
2584129              Cont'd attempts collect debt not owed   
2584130           Loan modification,collection,foreclosure   
2584131           Credit reporting company's investigation   
2584132             Incorrect information on credit report   
2584133                     Trouble during payment process   

                                                 Sub-issue  \
0                     Investigation took more than 30 days   
1                      Information belongs to someone else   
2                     Investigation took more than 30 days   
3        Their investigation did not fix an error on yo...   
4                                                      NaN   
...                                                    ...   
2584129                  Debt resulted from identity theft   
2584130                                                NaN   
2584131           No notice of investigation status/result   
2584132                                     Account status   
2584133                                                NaN   

                              Consumer complaint narrative  \
0                                                      NaN   
1                                                      NaN   
2                                                      NaN   
3                                                      NaN   
4                                                      NaN   
...                                                    ...   
2584129  I have disputed my debts several times with no...   
2584130  My father died in XX/XX/XXXX. Left me his only...   
2584131  cfbp i would Like to file a complaint on Exper...   
2584132  My husband and I are in the middle of an FHA S...   
2584133                                                NaN   

                                   Company public response  \
0        Company has responded to the consumer and the ...   
1                                                      NaN   
2                                                      NaN   
3                                                      NaN   
4        Company has responded to the consumer and the ...   
...    

### Product column of the dataframe assiggn to a variable

In [23]:
tf_str = tf.Variable(Df['Product'])

In [24]:
tf_str

<tf.Variable 'Variable:0' shape=(2584134,) dtype=string, numpy=
array([b'Credit reporting, credit repair services, or other personal consumer reports',
       b'Credit reporting, credit repair services, or other personal consumer reports',
       b'Credit reporting, credit repair services, or other personal consumer reports',
       ..., b'Credit reporting', b'Credit reporting', b'Mortgage'],
      dtype=object)>

In [26]:
tf1_str = tf.Variable(Df['Company'])

In [27]:
tf1_str

<tf.Variable 'Variable:0' shape=(2584134,) dtype=string, numpy=
array([b'TRANSUNION INTERMEDIATE HOLDINGS, INC.', b'EQUIFAX, INC.',
       b'EQUIFAX, INC.', ..., b'Experian Information Solutions Inc.',
       b'TRANSUNION INTERMEDIATE HOLDINGS, INC.',
       b'WELLS FARGO & COMPANY'], dtype=object)>

In [29]:
tf1_str.dtype

tf.string

In [30]:
tf1_str.numpy()

array([b'TRANSUNION INTERMEDIATE HOLDINGS, INC.', b'EQUIFAX, INC.',
       b'EQUIFAX, INC.', ..., b'Experian Information Solutions Inc.',
       b'TRANSUNION INTERMEDIATE HOLDINGS, INC.',
       b'WELLS FARGO & COMPANY'], dtype=object)