## How to create ones element using tensorflow

### Import tensorflow library

In [1]:
import tensorflow as tf

In [3]:
ones_3D=tf.ones((3, 3), tf.float32)
ones_3D

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [4]:
ones_tf=tf.ones((3, 3, 4), tf.float32)
ones_tf

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

## tf.ones_like()

Create a tensor of all ones that has the same shape as an input 

In [6]:
cons_2D = tf.constant([[1, 2, 3], [5, 6, 7]])
cons_2D

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

In [9]:
ones_2D_from_cons=tf.ones_like(cons_2D, tf.float32)
ones_2D_from_cons

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
ones1_2D_from_cons=tf.ones_like(cons_2D, tf.int32)
ones1_2D_from_cons

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [13]:
ones2_2D_from_cons=tf.ones_like(cons_2D, tf.int64)
ones2_2D_from_cons

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)>

## tf.ones_initializer

Initializer that generates tensors initialized to 1.

Initializers allow you to pre-specify an initialization strategy, 
encoded in the Initializer object, without knowing the shape and dtype of the variable being initialized.

In [14]:
def ones_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape=shape, dtype=dtype))

In [15]:
ones_variable((2, 2), tf.int32, tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

In [16]:
ones_variable((2, 2), tf.float32, tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>