## tensorflow Zeros, Zeros_like and Zeros_initializer methods

## Import library tensorflow

In [1]:
import tensorflow as tf

Creates a tensor with all elements set to zero.

In [2]:
zeros_set=tf.zeros((2, 2), dtype=tf.float32)
zeros_set

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [3]:
zeros_set.shape

TensorShape([2, 2])

In [4]:
zeros_set.dtype

tf.float32

In [5]:
zeros_set.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [7]:
zeros_set.numpy().tolist()

[[0.0, 0.0], [0.0, 0.0]]

## Zeros_like

Creates a tensor with all elements set to zero.

In [8]:
tf_cons=tf.constant([[2, 3, 4],[4, 5, 6],[5, 6, 7]])
tf_cons

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])>

In [10]:
tf_zeros_like_from_tf_cons=tf.zeros_like(tf_cons)
tf_zeros_like_from_tf_cons

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [11]:
tf_var = tf.Variable([[1, 2, 3], [5, 6, 7]])
tf_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

In [12]:
Zeros_like_for_tf_var=tf.zeros_like(tf_var)
Zeros_like_for_tf_var

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [13]:
Zeros_like_for_tf_var.shape

TensorShape([2, 3])

In [14]:
Zeros_like_for_tf_var.dtype

tf.int32

In [15]:
Zeros_like_for_tf_var.numpy()

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
Zeros_like_for_tf_var.numpy().tolist()

[[0, 0, 0], [0, 0, 0]]

##### Initializer that generates tensors initialized to 0.

Initializers allow you to pre-specify an initialization strategy, encoded in the Initializer object, without knowing the shape and dtype of the variable being initialized.

In [17]:
def zeros_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape=shape, dtype=dtype))

In [25]:
zi_1=zeros_variable((3, 4), tf.float32, tf.zeros_initializer())
zi_1

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [26]:
zi_2=zeros_variable((3, 3), tf.int32, tf.zeros_initializer())
zi_2

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [27]:
zi_1.shape

TensorShape([3, 4])

In [28]:
zi_2.shape

TensorShape([3, 3])

In [29]:
zi_2.numpy()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Create boolean initializer

In [31]:
zeros_bi=zeros_variable((2, 2), tf.bool, tf.zeros_initializer())
zeros_bi

<tf.Variable 'Variable:0' shape=(2, 2) dtype=bool, numpy=
array([[False, False],
       [False, False]])>

In [32]:
zeros_bi.shape

TensorShape([2, 2])

In [33]:
zeros_bi.dtype

tf.bool