## How to do multiplication in tensorflow 

#### tf.multiply()

We use above function for element wise multiplication

## Import libraries

In [1]:
import numpy as np
import tensorflow as tf

## Scaler multiply

In [2]:
a=10
b=3
tf.multiply(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

## Multiply two lists

In [3]:
l1=[1, 2, 3, 4]
l2=[5, 4, 2, 6]
tf.multiply(l1, l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5,  8,  6, 24])>

## Multiply two tuples

In [4]:
t1=(2, 3, 4, 6)
t2=(3, 6, 7, 8)
tf.multiply(t1, t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6, 18, 28, 48])>

## Multiply scaler with list

In [5]:
lst=[1, 2, 3, 4]
a=3
tf.multiply(lst, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  6,  9, 12])>

## Multiply scaler with tuple

In [6]:
t1=(2, 3, 4, 6)
a=2
tf.multiply(t1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4,  6,  8, 12])>

## Multiplication of two numpy arrays

In [7]:
np_ar1 = np.array([3, 4, 5])
np_ar2=np.array([4, 5, 6])
tf.multiply(np_ar1, np_ar2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 20, 30])>

## Multiply numpy array and scaler

In [8]:
np_ar1 = np.array([3, 4, 5])
a=10
tf.multiply(np_ar1, a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([30, 40, 50])>

## Multiply numpy array with single numpy array

In [9]:
np_ar1 = np.array([3, 4, 5])
np_arr2=np.array([3])
tf.multiply(np_ar1, np_arr2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 12, 15])>

## Multiply two tensor constant

In [10]:
tf_cn1=tf.constant([2, 3, 4])
tf_cn2=tf.constant([4, 5, 8])
tf.multiply(tf_cn1, tf_cn2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 15, 32])>

## Multiply tensor scaler value

In [11]:
tf_cn1=tf.constant([2, 3, 4])
a=2
tf.multiply(tf_cn1, a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 6, 8])>

## Multiply two tensor variables

In [12]:
tf_vr1=tf.Variable([3, 5, 7])
tf_vr2=tf.Variable([2, 4, 6])
tf.multiply(tf_vr1, tf_vr2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 20, 42])>

## Multiply scaler with tensorflow variables

In [14]:
tf_vr1=tf.Variable([3, 5, 7])
b=10
tf.multiply(tf_vr1, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([30, 50, 70])>

## How to do division of tensors in tensorflow

tf.divide()

We use the above divide function for tesnors division with element wise

## Scalers division

In [20]:
a=10
b=5
tf.divide(a,b)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

## Divide two lists using tensorflow divide function

In [16]:
l1=[2, 3, 4, 5]
l2=[2, 3, 2, 1]
tf.divide(l1, l2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 1., 2., 5.])>

## Divide two tuples

In [17]:
t1=(22, 11, 33)
t2=(11, 1, 11)
tf.divide(t1, t2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 2., 11.,  3.])>

## Divide list by scaler

In [18]:
lst=[2, 3, 4, 5]
a=2
tf.divide(lst, a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1. , 1.5, 2. , 2.5])>

## Divide tuple by scaler

In [19]:
tup1=(2, 4, 6)
b=2
tf.divide(tup1, b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

## Divide two numpy arrays

In [21]:
np_arr1=np.array([4, 6, 8])
np_arr2=np.array([2, 3, 4])
tf.divide(np_arr1, np_arr2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 2., 2.])>

## Divide numpy array by scaler

In [22]:
np_arr1=np.array([4, 6, 8])
b=2
tf.divide(np_arr1, b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

## Divide two tensorflow constant 

In [24]:
tf_cons1=tf.constant([2, 3, 4])
tf_cons2=tf.constant([4, 5, 8])
tf.divide(tf_cons1, tf_cons2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.5, 0.6, 0.5])>

## Divide tensor constant by scaler

In [25]:
tf_cons1=tf.constant([2, 3, 4])
b=2
tf.divide(tf_cons1, b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1. , 1.5, 2. ])>

## Divide two tensor variables 

In [26]:
tf_vr1=tf.Variable([3, 5, 7])
tf_vr2=tf.Variable([2, 4, 6])
tf.divide(tf_vr1, tf_vr2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.5       , 1.25      , 1.16666667])>

## Divide tensor variable by scaler

In [27]:
tf_vr1=tf.Variable([3, 5, 7])
b=10
tf.divide(tf_vr1, b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.3, 0.5, 0.7])>