## Mathematical operations using deep learning tesnorflow.

### Add function.

tf.add(): Returns x + y element-wise.

## Import libraries

In [1]:
import numpy as np
import tensorflow as tf

## Simple addition

In [2]:
a = 23
b = 27
c = a + b
print(c)

50


In [3]:
# Using tensorflow tf.add()
tf.add(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

## Create two lists and its addition

In [4]:
list1=[2, 3, 4, 5]
list2=[4, 5, 7, 8]
tf.add(list1, list2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 11, 13])>

## Create two tuples and find its addition

In [5]:
tuple1=(2, 3, 4, 5)
tuple2=(3, 4, 5, 6)
tf.add(tuple1, tuple2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5,  7,  9, 11])>

## Addition of tuple and list using tensorflow add function

In [6]:
tf.add(list1, tuple1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4,  6,  8, 10])>

## Addition of two numpy array using tensorflow add function

In [7]:
np_a1=np.array([1, 2, 3])
np_a2=np.array([3, 4, 5])
tf.add(np_a1, np_a2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 6, 8])>

## Add numpy array with scaler

In [9]:
np_a1=np.array([1, 2, 3])
b=15
tf.add(np_a1, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([16, 17, 18])>

## Add numpy array with single element

In [10]:
np_ar1=np.array([1, 2, 3])
np_ar2=np.array([3])
tf.add(np_ar1, np_ar2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

## Add two tensorflow constant

In [12]:
tf_con1=tf.constant([2, 3, 4])
tf_con2=tf.constant([3,4, 5])
tf.add(tf_con1, tf_con2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

## Add tensorflow constant with scaler

In [13]:
tf_cons1=tf.constant([2, 3, 4])
b=12
tf.add(tf_cons1, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([14, 15, 16])>

## Add two tensorflow variables

In [14]:
tf_var1=tf.Variable([2, 3, 4, 5])
tf_var2=tf.Variable([3, 5, 7, 9])
tf.add(tf_var1, tf_var2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5,  8, 11, 14])>

## Add tensorflow variable and scaler

In [15]:
tf_var=tf.Variable([3, 5, 7, 9])
a=12
tf.add(tf_var, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([15, 17, 19, 21])>

## Add two tensorflow zeros and ones function 

In [16]:
tf_ones=tf.ones((3, 3), tf.int32)
tf_zeros=tf.zeros((3, 3), tf.int32)
tf.add(tf_ones, tf_zeros)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])>

## Add tensorflow ones function and scaler

In [17]:
tf_ones1=tf.ones((3, 3), tf.int32)
b=10
tf.add(tf_ones1, b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])>

## How to subtrct Tensors in tensorflow

#### tf.subtract()

Element wise subtraction in tensorflow

## Two Scalers subtraction

In [18]:
a=10
b=5
tf.subtract(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

## Subtract two lists

In [19]:
l1=[3, 5, 6, 8]
l2=[2, 4, 5, 6]
tf.subtract(l1, l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 1, 2])>

## Subtract scaler from list

In [22]:
l1=[3, 5, 6, 8]
a=2
tf.subtract(l1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 3, 4, 6])>

## Subtract two tuples

In [20]:
t1=(3, 5, 7, 9)
t2=(5, 3, 5, 7)
tf.subtract(t1, t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-2,  2,  2,  2])>

## Subtract scaler from tuple

In [21]:
t1=(3, 5, 7, 9)
a=3
tf.subtract(t1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 2, 4, 6])>

## Subtract two numpy arrays

In [23]:
arr1=np.array([4, 5, 6])
arr2=np.array([1, 2, 3])
tf.subtract(arr1, arr2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 3, 3])>

## Subtract scaler from numpy array

In [24]:
arr1=np.array([4, 5, 6])
a=10
tf.subtract(arr1, a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-6, -5, -4])>

## Subtract single numpy array from numpy array

In [25]:
arr1=np.array([4, 5, 6])
arr2=np.array([2])
tf.subtract(arr1, arr2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

## Subtraction of two constant tensors

In [26]:
tf_const1=tf.constant([2, 5, 7])
tf_const2=tf.constant([1, 3, 5])
tf.subtract(tf_const1, tf_const2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 2])>

## Subtract scaler value from tensorflow constant

In [27]:
tf_const1=tf.constant([2, 5, 7])
b=1
tf.subtract(tf_const1, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 6])>

## Subtract two tensorflow variables 

In [28]:
tf_var1=tf.Variable([4, 5, 6])
tf_var2=tf.Variable([1, 2, 3])
tf.subtract(tf_var1, tf_var2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 3, 3])>

## Subtract scaler from tensorflow variables

In [29]:
tf_var1=tf.Variable([4, 5, 6])
a=3
tf.subtract(tf_var1, a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>